# Generated by Django 4.2 on 2023-04-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tododbmodel',
            name='status',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('Done', 'Done'), ('NotStarted', 'NotStarted')], default='NotStarted', max_length=10),
        ),
    ]
